# Generated by Django 4.0.4 on 2022-05-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_user_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Knowledge', 'Knowlegde')], max_length=200, null=True),
        ),
    ]
