# Generated by Django 4.0.4 on 2022-05-08 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('book', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.book')),
                ('customer', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
            ],
        ),
    ]
