# Generated by Django 4.0.4 on 2022-05-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_review_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='books',
        ),
        migrations.RemoveField(
            model_name='review',
            name='category',
        ),
    ]
