# Generated by Django 4.0.4 on 2022-05-19 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_book_review_books_remove_review_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Review',
            field=models.ForeignKey(max_length=500, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.review'),
        ),
    ]
