# Generated by Django 4.0.4 on 2022-05-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Rented', 'Rented'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], max_length=200, null=True),
        ),
    ]
