# Generated by Django 4.0.4 on 2022-05-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cost',
        ),
    ]
