# Generated by Django 4.0.4 on 2022-05-22 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_review_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Review',
            field=models.OneToOneField(max_length=500, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.review'),
        ),
    ]
