# Generated by Django 4.0.4 on 2022-05-22 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0022_alter_order_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='datecreated',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AlterField(
            model_name='order',
            name='book',
            field=models.OneToOneField(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.book'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.OneToOneField(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
