# Generated by Django 4.0.4 on 2022-05-22 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_order_datecreated_remove_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Rented', 'Rented'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Review',
            field=models.ForeignKey(max_length=500, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.review'),
        ),
        migrations.AlterField(
            model_name='order',
            name='book',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.book'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
    ]
