# Generated by Django 4.0.4 on 2022-05-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Review',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
