# Generated by Django 4.0.4 on 2022-05-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_order_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
