# Generated by Django 4.0.4 on 2022-06-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_book_book_category_book_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
