# Generated by Django 4.0.4 on 2022-06-03 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(choices=[('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Knowledge', 'Knowlegde')], max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.category'),
        ),
    ]
