# Generated by Django 4.0.4 on 2022-06-06 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0040_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Review',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.TextField(max_length=500, null=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('book', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
