# Generated by Django 4.0.4 on 2022-06-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_rename_desc_book_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
