# Generated by Django 4.0.4 on 2022-06-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Rented', 'Rented'), ('Pending', 'Pending'), ('Returned', 'Returned')], max_length=200, null=True),
        ),
    ]
