# Generated by Django 4.0.4 on 2022-06-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_rename_datecreated_order_dateordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dimennsions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
