# Generated by Django 4.0.4 on 2022-06-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_book_dimennsions_book_language_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
