# Generated by Django 4.0.6 on 2022-07-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Review',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
