# Generated by Django 4.0.6 on 2022-07-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='Review',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
